Feat/chat gpt complement
ensan-hcl/azooKey-Desktop pull request #78
Opened 2024-09-30 13:27 UTC by nyanko3141592

ChatGPT APIを利用して文章補完機能を実装

- ChatGPT APIのConfig設定を追加
- SuggestionViewで補完Windowを追加

2024-09-30 14:22 UTC, ensan-hcl requested changes

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +    func submitSelectedComplement() {
これhideSuggestionに対応させるならsubmitSelectedSuggestionじゃない？

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +    }
これ使わないなら消してよさそう、将来的に何か処理をここに書いていくイメージだったらその旨コメントとして残して

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        return lines.joined(separator: "\n")
この`.map { "\($0)" }`って何？多分要らなくない？

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +                hideSuggestion()
self.ってつけるのかつけないのか揃えてほしい

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +                self.hideChatGPTView()
これ実装がないのに呼び出してるけど不要な処理？

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/Actions/ClientAction.swift
> +
`requestSuggestion`と`submitSuggestion`じゃダメ？ChatGPTは実装の詳細だと思う（GeminiのAPIを呼ぶようになったらここの名前が変わるのかというとなんか変な気がしない？）

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/Configs/BoolConfigItem.swift
> +    }
思ったけどこれUserDefaultsに保存してるの普通にセキュアじゃないよね（このあとのPRでは少なくとも修正すべき）

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/Actions/UserAction.swift
> +    case shortcut
このshortcutって抽象的であまりよくわからなかったんだけど、どういうものをここに入れるつもりでいる？

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/InputState.swift
> +        isSuggestionDisplayed: Bool
isSuggestionDisplayedは`InputMode`に入れたほうがシンプルだと思う。つまり`none`から`suggestion`に遷移、確定すると`suggestion`から`none`に戻る。`suggestion`の状態では`tab`の解釈を変える

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +class OpenAIClient {
`final`つけて

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +}
この辺の型ってprivateにできない？`ErrorUnion`とか`Message`とか割と使いがちな名前だし可視性コントロールしたい

2024-09-30 14:22 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +            if Config.EnableOpenAiApiKey().value && Config.OpenAiApiKey().value.isEmpty == false {
このチェックって`self.requestChatGPT()`の中でももう一回やっってるけど、なんかどっちかに寄せていいんじゃない？

2024-09-30 23:52 UTC, ensan-hcl requested changes

2024-09-30 23:52 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +final class OpenAIClient {
これそもそもクラスが状態を持ってないと思うんだけど、enum+static funcのパターンじゃダメだった？シングルトンにする必要はある？

2024-09-30 23:52 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +                    if let contentData = contentString.data(using: .utf8) {
この辺だいぶネスト深いけどifじゃなくてguardでearly continueしたら読みやすくならない？かなり厳しい

2024-09-30 23:52 UTC, ensan-hcl commented on azooKeyMac/InputController/SuggestionView.swift
> +class Suggestion: NSView {
Viewの名前としては汎用的すぎだと思う

2024-10-01 07:28 UTC, nyanko3141592 commented on azooKeyMac/InputController/SuggestionView.swift
> +class Suggestion: NSView {
SuggestionViewに変更

2024-10-01 07:29 UTC, nyanko3141592 commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +            if Config.EnableOpenAiApiKey().value && Config.OpenAiApiKey().value.isEmpty == false {
case .requestChatGPT:に寄せる

2024-10-01 07:29 UTC, nyanko3141592 commented on azooKeyMac/InputController/OpenAIClient.swift
> +final class OpenAIClient {
enum+static funcに修正

2024-10-01 12:49 UTC, ensan-hcl commented on azooKeyMac.xcodeproj/project.pbxproj
> -		55CE92532C9FC08100C38E1B /* UserDictionaryEditorWindow.swift in Sources */ = {isa = PBXBuildFile; fileRef = 55CE92522C9FC08100C38E1B /* UserDictionaryEditorWindow.swift */; };
これ消えててビルド通らない

2024-10-01 12:50 UTC, ensan-hcl commented on azooKeyMac.xcodeproj/project.pbxproj
> -		55CE92522C9FC08100C38E1B /* UserDictionaryEditorWindow.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = UserDictionaryEditorWindow.swift; sourceTree = "<group>"; };
ここも消えてちゃダメだと思う、ビルド普通に通らなくなってる

2024-10-01 12:50 UTC, ensan-hcl commented on azooKeyMac.xcodeproj/project.pbxproj
> -				55CE92522C9FC08100C38E1B /* UserDictionaryEditorWindow.swift */,
同じく

2024-10-01 12:51 UTC, ensan-hcl commented on azooKeyMac.xcodeproj/project.pbxproj
> -				55CE92532C9FC08100C38E1B /* UserDictionaryEditorWindow.swift in Sources */,
同じく

2024-10-01 12:51 UTC, ensan-hcl commented on azooKeyMac.xcodeproj/project.pbxproj
> -				revision = 8cf7aabf630f71f3b3cb617e959e4ea2ea01f5a1;
このリビジョン変更って何か意図ある？

2024-10-01 12:54 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +    }
使われてないので削除でいいはず

2024-10-01 12:54 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +
要らない差分

2024-10-01 12:56 UTC, ensan-hcl requested changes

2024-10-01 12:56 UTC, ensan-hcl commented on azooKeyMac/Windows/ConfigWindow.swift
> +                                helpContent: "OpenAPIキーはローカルのみで管理され、外部に公開されることはありません。生成の際にAPIを利用するため、課金が発生します。",
OpenAPIキー → OpenAI APIキー

2024-10-02 07:27 UTC, nyanko3141592 commented on azooKeyMac/Configs/BoolConfigItem.swift
> +    }
そうだね

2024-10-02 09:08 UTC, nyanko3141592 commented on azooKeyMac.xcodeproj/project.pbxproj
> -				revision = 8cf7aabf630f71f3b3cb617e959e4ea2ea01f5a1;
ないので戻した

2024-10-02 09:09 UTC, nyanko3141592 commented on azooKeyMac/Configs/BoolConfigItem.swift
> +    }
後でissueにして対応

2024-10-02 14:28 UTC, ensan-hcl approved these changes
めっちゃいい！ナイス！！

2024-10-02 14:28 UTC, merged

2024-10-06 12:10 UTC, diskshima commented on azooKeyMac/InputController/CandidateView.swift
> +            maxWidth + 32
@nyanko3141592 
こちら、自分の変更が戻されているのですが、何かまずかったですかね…？
#76

2024-10-06 12:58 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateView.swift
> +            maxWidth + 32
おっと…… @nyanko3141592 がマージでミスってて自分が気づかず通した感じですね。

2024-10-06 13:04 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateView.swift
> +            maxWidth + 32
このPRはSquash Mergeしちゃってたので、@diskshima さんのコミットをcherry-pickして再マージしました！

2024-10-06 13:06 UTC, nyanko3141592 commented on azooKeyMac/InputController/CandidateView.swift
> +            maxWidth + 32
@diskshima 
マージの時にミスりました！すいません！
内容は全然問題なかったです！

2024-10-07 12:47 UTC, diskshima commented on azooKeyMac/InputController/CandidateView.swift
> +            maxWidth + 32
@ensan-hcl @nyanko3141592 
いえいえ、修正ありがとうございます！