feat: ChatGPTによる変換候補の提案機能
ensan-hcl/azooKey-Desktop pull request #86
Opened 2024-11-25 17:40 UTC by nyanko3141592

- composingの状態でctrl + sでChatGPTからconvertTargetの変換候補を取得できる機能
- えもじ、きごう、えいごなどの特定ワードはpromptを切り分けて利用可能

2024-11-26 05:26 UTC, ensan-hcl requested changes

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +let sharedPromptText: String = " Output multiple candidates. The prompt is as follows:"
これもprivateにしたい気がする。あるいはOpenAIRequestのstatic letにするとか。

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +    let defaultPrompt: String = "Replace the text enclosed in <> in the article with the most suitable form for the previous sentence. If the same content as the preceding text is received, convert i
このdefault promptはstaticにしない？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +private var promptDictionary: [String: String] = [
OpenAIRequestのstatic letにしない？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +    private func adjustedPrompt() -> String {
関数名、adjustedPrompt()にするか、get-only propertyにしてvar adjustedPrompt: String { ... }の方がいい気がする

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +                                    "description": "Replace text"
ここってdescriptionであるなら「Replaced text」じゃない？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> -                I want you to generate possible sentence completions for a given sentence fragment. The output should be a list of different possible endings for the fragment. For example, if I provi
この以前の続き予測promptは消えちゃってるけど、この挙動は維持できてる？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/InputState.swift
> +    case suggesting
suggestingとsuggestionの違いがわからん……

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateView.swift
> +
余計な差分

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateView.swift
> -        // 右端でウィンドウが画面外に出る場合は左にシフト
これって消す意味あるの？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateView.swift
> -        // 画面のサイズを取得
同じく消す意味がない気がする、このファイルで消してるところって意味があって消してる？

2024-11-26 05:26 UTC, ensan-hcl commented on azooKeyMac/InputController/SuggestCandidatesViewController.swift
> +class SuggestCandidatesViewController: BaseCandidateViewController {
Suggest / Suggestion / Suggestingの違いがよくわからないのでどこに明示的な説明を書くか、あるいはもう少し違うものに見えるような名前を付けてほしい

2024-11-27 11:14 UTC, nyanko3141592 commented on azooKeyMac/InputController/OpenAIClient.swift
> +                                    "description": "Replace text"
修正

2024-11-27 11:15 UTC, nyanko3141592 commented on azooKeyMac/InputController/OpenAIClient.swift
> -                I want you to generate possible sentence completions for a given sentence fragment. The output should be a list of different possible endings for the fragment. For example, if I provi
一応ある程度維持できてる
ただ今回のブランチで予測入力のプロンプト変更は不要なので修正

2024-11-29 14:01 UTC, ensan-hcl commented on azooKeyMac/InputController/CandidateWindow/BaseCandidateViewController.swift
> +//  BaseCandidateViewController.swift
（本来無関係な差分は入れたくないんだけど）こういうの虚無だし上5行消しちゃわない？

2024-11-29 14:02 UTC, nyanko3141592 commented on azooKeyMac/InputController/CandidateWindow/BaseCandidateViewController.swift
> +//  BaseCandidateViewController.swift
消していいと思う

2024-11-29 14:13 UTC, ensan-hcl commented on azooKeyMac/InputController/OpenAIClient.swift
> +    let target: String
どっちが何なのかよくわからないのでdocument commentつけてほしい

2024-11-29 14:14 UTC, ensan-hcl commented on azooKeyMac/InputController/SegmentsManager.swift
> +    private var suggestSelectionIndex: Int?
プロパティはclassの先頭で宣言してほしいかも

2024-11-29 14:16 UTC, ensan-hcl requested changes

2024-11-29 14:16 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        self.suggestCandidateWindow.orderOut(nil)
このへんまだsuggestionとsuggestの違いがわかりにくくなってるから直してほしい

2024-11-30 13:35 UTC, nyanko3141592 commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        self.suggestCandidateWindow.orderOut(nil)
わかりにくいのでsuggestCandidateをreplaceCandaidateに変更した
むしろsuggestionの方が名前悪いかも

2024-11-30 14:14 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        self.suggestCandidateWindow.orderOut(nil)
うーん？replaceSuggestionCandidateとpredictiveSuggestionCandidateにすれば？
あと、replacingSuggestionとrequestReplaceSuggestionがあるのも直したい

2024-11-30 14:15 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        self.suggestCandidateWindow.orderOut(nil)
それでいうと「case requestSuggestion」も嫌かも、`requestPredictiveSuggestion`にしたい

2024-11-30 14:15 UTC, ensan-hcl commented on azooKeyMac/InputController/azooKeyMacInputController.swift
> +        self.suggestCandidateWindow.orderOut(nil)
全体として命名は一貫させてほしいんだ

2024-11-30 14:16 UTC, ensan-hcl commented
@nyanko3141592 docstringの書き方は`///`で始めるXcode式のやつを使ってほしい

2024-11-30 15:46 UTC, ensan-hcl commented
「replacingSuggestion」が治ってない

2024-11-30 16:04 UTC, ensan-hcl approved these changes
一旦mergeしよう！

2024-11-30 16:05 UTC, merged